package com.example.springsecurityapplication.controllers;


import com.example.springsecurityapplication.models.Product;
import com.example.springsecurityapplication.repositories.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

// @Controller + @ResponseBody
@RestController
@RequestMapping("/api")
public class ApiController {

    private final ProductRepository productRepository;

    @Autowired
    public ApiController(ProductRepository productRepository) {
        this.productRepository = productRepository;
    }


    // http://localhost:8080/api/info

    /*
create table product(
id int primary key generated by default as identity,
name varchar(100) not null,
price float not null

insert into product(name, price) values('Стол', 10000);
insert into product(name, price) values ('Стул', 2500);
);
     */
    // Данный метод API позволяет узнать информацию об api
    @GetMapping("/inf")
    public String getInfoApi(){
        return "Данное API предназначено для работы с товарами";
    }

    @GetMapping("/productIp")
    public List<Product> getProduct(){
        return productRepository.findAll(); // С помощью библиотеки Jackson конвертируем эти объекты в JSON
    }

    @GetMapping("/productIp/search/{id}")
    public Optional<Product> getProductId(@PathVariable("id") int id){
        return productRepository.findById(id);
    }

    @GetMapping("/productIp/delete/{id}")
    public String deleteProductId(@PathVariable("id") int id){
        productRepository.deleteById(id);
        return "Товар успешно удален";
    }

}
